version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=highload'
      - 'POSTGRES_PASSWORD=high_user'
      - 'POSTGRES_USER=high_user'
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    restart: unless-stopped

  config:
    image: config:latest
    container_name: config
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  eureka:
    image: eureka:latest
    container_name: eureka
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config

  gateway:
    image: gateway:latest
    container_name: gateway
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  login-service:
    image: login-service:latest
    container_name: login-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gateway

  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - login-service

  admin-service:
    image: admin-service:latest
    container_name: admin-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8182:8182"
    depends_on:
      - login-service
      - user-service

  order-service:
    image: order-service:latest
    container_name: order-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8183:8183"
    depends_on:
      - login-service
      - user-service

  image-service:
    image: image-service:latest
    container_name: image-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./image-service
      dockerfile: Dockerfile
    ports:
      - "8185:8185"
    depends_on:
      - login-service
      - user-service

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=ereboging'
      - 'JWT_EXPIRED=84600'
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8184:8184"
    depends_on:
      - login-service
      - user-service

#  profile-service:
#    image: profile-service:latest
#    container_name: profile-service
#    environment:
#      - 'PAGINATION_MAX_SIZE=50'
#      - 'JWT_SECRET=ereboging'
#      - 'JWT_EXPIRED=84600'
#    build:
#      context: ./profile-service
#      dockerfile: Dockerfile
#    ports:
#      - "8186:8186"
#    depends_on:
#      - login-service
#      - user-service
