version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=highload'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    restart: unless-stopped

  config:
    image: config:latest
    container_name: config
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  eureka:
    image: eureka:latest
    container_name: eureka
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config

  gateway:
    image: gateway:latest
    container_name: gateway
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  login-service:
    image: login-service:latest
    container_name: login-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    depends_on:
      - gateway

  admin-service:
    image: admin-service:latest
    container_name: admin-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8182:8182"
    depends_on:
      - login-service


  user-service:
    image: user-service:latest
    container_name: user-service
    environment:
      - 'PAGINATION_MAX_SIZE=50'
      - 'JWT_SECRET=itmo'
      - 'JWT_EXPIRED=15'
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - login-service
