server:
  port: 8185
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://localhost:5432/highload
    username: high_user
    password: high_user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: ereboging
  expired: 84600
pagination:
  maxSize: 50

