server:
  port: 8181
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://postgres:5432/highload
    username: high_user
    password: high_user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    enabled: true
    drop-first: false
    default-schema: public
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: ${JWT_SECRET}
  expired: ${JWT_EXPIRED}
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}

